### ISSUE TITLE
Change read.csv to read_csv in rmarkdown lessons

### ISSUE THREAD

**Issue by boshek** [bcgov/ds-intro-to-r-2-day#10]

**Comment by ateucher** [comment]
@gcperk I think you did this?

**Comment by boshek** [comment]
Maybe fixed in a branch but still some instances here too? https://github.com/bcgov/ds-intro-to-r-2-day/blob/9c5ed4a88c64a49510fd8e4c77a5e87800be6813/04-data-structures-part1.Rmd#L320-L342

Obviously not rmarkdown but the issue still applies "globally"?

**Comment by ateucher** [comment]
Yup, I'm fixing that in my branch
